[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=4.2.1",
    "colorama>=0.4.6",
    "flask>=3.1.0",
    "rich>=13.9.4",
]
